{"hierarchy":{"paths":[["doc:\/\/TapyrusWallet\/documentation\/TapyrusWallet","doc:\/\/TapyrusWallet\/documentation\/TapyrusWallet\/SyncError"]]},"abstract":[{"text":"Occur if the esplora client fails to connect","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EsploraClientError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"causeDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/TapyrusWallet\/documentation\/TapyrusWallet\/SyncError\/EsploraClientError(causeDescription:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tapyruswallet\/syncerror\/esploraclienterror(causedescription:)"]}],"kind":"symbol","metadata":{"symbolKind":"case","roleHeading":"Case","externalID":"s:13TapyrusWallet9SyncErrorO013EsploraClientD0yACSS_tcACmF","role":"symbol","title":"SyncError.EsploraClientError(causeDescription:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EsploraClientError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"causeDescription","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"modules":[{"name":"TapyrusWallet"}]},"references":{"doc://TapyrusWallet/documentation/TapyrusWallet/SyncError":{"role":"symbol","type":"topic","identifier":"doc:\/\/TapyrusWallet\/documentation\/TapyrusWallet\/SyncError","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SyncError"}],"title":"SyncError","abstract":[{"type":"text","text":"The error for HDWallet#sync"}],"url":"\/documentation\/tapyruswallet\/syncerror","navigatorTitle":[{"text":"SyncError","kind":"identifier"}]},"doc://TapyrusWallet/documentation/TapyrusWallet/SyncError/EsploraClientError(causeDescription:)":{"title":"SyncError.EsploraClientError(causeDescription:)","type":"topic","role":"symbol","identifier":"doc:\/\/TapyrusWallet\/documentation\/TapyrusWallet\/SyncError\/EsploraClientError(causeDescription:)","kind":"symbol","abstract":[{"type":"text","text":"Occur if the esplora client fails to connect"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"EsploraClientError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"causeDescription","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"url":"\/documentation\/tapyruswallet\/syncerror\/esploraclienterror(causedescription:)"},"doc://TapyrusWallet/documentation/TapyrusWallet":{"type":"topic","abstract":[],"title":"TapyrusWallet","kind":"symbol","url":"\/documentation\/tapyruswallet","identifier":"doc:\/\/TapyrusWallet\/documentation\/TapyrusWallet","role":"collection"}}}